### ISSUE TITLE
SubjectCNMapping doesn't not manage correctly  "Special Characters" like , (comma)

### ISSUE THREAD

**Issue by gautric** [picketbox/picketbox#27]
If we have a certificate with a DN like this 
"CN=Picketbox\, vault 2, OU=picketbox, O=JBoss, L=chicago, ST=il, C=us" (comma after Picketbox)
we get a Principal with ["picketbox] name instead of [Picketbox, vault 2]

**Comment by gautric** [comment]
take a look at https://issues.jboss.org/browse/SECURITY-875

**Comment by sguilhen** [comment]
Good catch, there's definitely an issue there. I'll review your PR and merge it.

**Comment by sguilhen** [comment]
Fix was merged and pushed upstream. Thanks!
