### ISSUE TITLE
JBossSecurityContext error in clone()

### ISSUE THREAD

**Issue by regnete** [picketbox/picketbox#29]
Line https://github.com/picketbox/picketbox/blob/master/security-jboss-sx/jbosssx/src/main/java/org/jboss/security/plugins/JBossSecurityContext.java#L367 seems to be wrong.

Wrong:
```java
return super.clone();
```

Correct
```java
return jsc;
```

**Comment by sguilhen** [comment]
Good catch, that is definitely wrong. I'll push a fix later today.

**Comment by sguilhen** [comment]
I've pushed a fix to upstream.
